### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by xiaohongniua** [Holy-Shine/Pytorch-notebook#1]
**thanks a lot for your code ,I understand more about attention in DL. however when I run the following code,I got this **

hidden_size = 256
encoder1 = EncoderRNN(input_lang.n_words, hidden_size).to(device)
attn_decoder1 = AttnDecoderRNN(hidden_size, output_lang.n_words, dropout_p=0.1).to(device)

trainIters(encoder1, attn_decoder1, 75000, print_every=5000)

**RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS**

I tried to fix it ,but failed,what might be the reason?

**Comment by Holy-Shine** [comment]
@xiaohongniua 
Maybe  your cudnn version is not suitable for your graphics card? BTW, r  u  Chinese? We can discuss in Chinese,,,,,,,,,

**Comment by xiaohongniua** [comment]
哈哈哈，好！


| |
刘小红
|
|
xiaohongniua@163.com
|
签名由网易邮箱大师定制
On 12/17/2018 01:14，西木野Maki<notifications@github.com> wrote：

Maybe your cudnn version is not suitable for your graphics card? BTW, r u Chinese? We can discuss in Chinese,,,,,,,,,
